### ISSUE TITLE
Not compatible with Laravel 4.1.26

### ISSUE THREAD

**Issue by syphernl** [ccovey/ldap-auth#30]
Using this module on 4.1.26 results in a fatal error:

```
Class Ccovey\LdapAuth\LdapAuthUserProvider contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Illuminate\Auth\UserProviderInterface::retrieveByToken, Illuminate\Auth\UserProviderInterface::updateRememberToken) 
```

**Comment by danjellesma** [comment]
Receiving the same error with new installs of Laravel. Simply declaring the class abstract didn't help

**Comment by syphernl** [comment]
I have worked around this problem by putting the missing functions (with arguments) in `LdapAuthUserProvider.php`. These functions are most likely useless, or should they actually be used (and thus requiring a users table to be used in the DB)

**Comment by jasonspick** [comment]
@syphernl Can you show me an example of what that looks like?

**Comment by syphernl** [comment]
I don't have access to the source from here but IIRC it was simply adding this to the class defined in `LdapAuthUserProvider.php`:

```
public function retrieveByToken($identifier, $token) {}
public function updateRememberToken($user, $token) {}
```

It works fine with this, not sure what I'm missing out on but I needed to fix my app pronto

**Comment by ccovey** [comment]
this is now fixed...the token stuff I just return because its not really needed for these purposes.

**Comment by syphernl** [comment]
Unfortunately the 1.1.5 release does not fix this issue as it is now missing `getRememberToken`, `setRememberToken` and `getRememberTokenName`. Also, a typo "extend" rather than "extends".

**Comment by robstel** [comment]
syphernl's fix works for me: 

revert to v1.1.4 in composer.json:

``` JSON
require {
    "ccovey/ldap-auth": "1.1.4",
}
```

add the following to LdapAuthUserProvider.php

``` PHP
public function retrieveByToken($identifier, $token) {}
public function updateRememberToken(Auth\UserInterface $user, $token) {}
```

The 1.1.5 changes break my app horribly, even after fixing the missing methods & typo in LdapUser.php .

I'm using a database Model, and 1.1.5 tries to find the user with 

``` PHP
$model = $this->createModel()->newQuery()->find($identifier);
```

where it was previously

``` PHP
$model = $this->createModel()->newQuery()->where($this->getUsernameField(), $identifier)->first();
```

As $identifier is the username, not an ID, this fails.

**Comment by aaronmaturen** [comment]
The getRememberToken, setRememberToken, getRememberTokenName got added in 4.1.28, I've added a pull request to fix that.
